config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to articles_path
  end

  def edit; end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container my-5">
  <%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

<!-- <div class="form-group">
  <%= f.label :content%>
  <textarea class="form-control" id="@article[content]" rows="3"></textarea>
</div> -->

    <%= f.label :content%>
    <%= f.text_field :content, class: 'form-control' %>

  <%= f.submit %>
  <% end %>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render "form" %>
<%= link_to 'show', article_path %> |
<%= link_to "Back", articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
 <h2><%= link_to article.title, article_path(article) %></h2>
 <p><%= article.content%></p>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form" %>
<%= link_to "Back", articles_path %>

app/views/articles/show.html.erb
<div class='d-flex align-items-center'>
  <h1 class="h1 text-monospace"><%= @article.title %></h1>
  <%= link_to "✏", edit_article_path%>
  <%= link_to "❌", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}%>
</div>
<img src="https://picsum.photos/500/200" alt="" class="img-fluid">
<br>
<div>
  <br>
  <p><%= @article.content %></p>
</div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="http://localhost:3000/articles">Wikinimous</a>
      <a class="navbar-brand" href="http://localhost:3000/articles/new">New Article</a>
    </nav>
    <div class="container p-3">
      <div class="row d-flex justify-content-center">
        <div class="col-sm-8 col-sm-offset-2">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>